name=DFRobot_Biometric
version=1.0.0
author=DFRobot
maintainer=Olive-hy<feng.yang@dfrobot.com>
sentence=This is a function library for face and palm vein recognition modules based on USART communication
paragraph=This library provides hardware-based functions to enroll both face and palm vein credentials, automatically detect and recognize users, delete users, send commands via USART, and read feedback information.
category=Sensors
url=https://github.com/cdjq/DFRobot_Biometric
architectures=*
