# stubs/gpiozero/__init__.pyi

class Button:
  def __init__(self, pin: int, pull_up: bool = True, bounce_time: float | None = None) -> None: ...
  def wait_for_press(self, timeout: float | None = None) -> None: ...
  def wait_for_release(self, timeout: float | None = None) -> None: ...
  @property
  def is_pressed(self) -> bool: ...
